spring:
  profiles: docker
server:
  port: 8765
  context-path: /v1
zuul:
  routes:
    metadata:
      path: /metadata/**
      service-id: coreapi-metadata
      strip-prefix: false
      sensitiveHeaders:
    products:
      path: /products/**
      service-id: coreapi-product
      strip-prefix: false
      sensitiveHeaders:
    collections:
      path: /collections/**
      service-id: coreapi-collection
      strip-prefix: false
      sensitiveHeaders:
    artifacts:
      path: /artifacts/**
      service-id: coreapi-artifact
      strip-prefix: false
      sensitiveHeaders:
proxy:
  auth:
    routes:
      metadata: passthru
      products: passthru
      collections: passthru
      artifacts: passthru
security:
  basic:
    enabled: false
logging:
  level:
    org.springframework.security.oauth2: DEBUG
eureka:
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/