spring:
  profiles: docker
server:
  port: 8765
  context-path: /v1
zuul:
  routes:
    metadata:
      path: /metadata/**
      service-id: coreapi-metadata
      strip-prefix: false
    templates:
      path: /templates/**
      service-id: coreapi-template
      strip-prefix: false
    artifacts:
      path: /artifacts/**
      service-id: coreapi-artifact
      strip-prefix: false
eureka:
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/